FROM arm32v7/node:8-slim

WORKDIR /app/

COPY package*.json ./

RUN npm install --production

COPY app.js ./
COPY src ./src

USER node

CMD ["node", "app.js"]
# CMD ["npm", "run", "nodemon"]

# RUN pwd
# RUN ls -al

# CMD ["./node_modules/.bin/nodemon", "./app.js", "--watch", "src"]
# CMD ["node", "./node_modules/nodemon/bin/nodemon.js", "./app.js", "--watch", "src"]